export const galleryInfo = [
  {
    id: 1,
    link1: '/gallery/img1.webp',
    link2: '/gallery/img2.webp',
    heading: 'Lawn Care',
    desc: 'Keep your garden looking beautiful without having to lift a finger With Reliable Gardening Professionals',
    width1: 60,
    width2: 40,
    section1Data: [
      'Mowing',
      'Edging',
      'Fertilization',
      'Topiary Services',
      'Mulching Services',
      'Aeration',
      'Lawn',
      'Detaching',
      'Slashing',
    ],
    section2Data: [
      'Mowing',
      'Edging',
      'Fertilization',
      'Topiary Services',
      'Mulching Services',
      'Aeration',
      'Lawn',
      'Detaching',
      'Slashing',
    ],
  },
  {
    id: 2,
    link1: '/gallery/img3.webp',
    link2: '/gallery/img4.webp',
    heading: 'Weed Control',
    desc: 'Keep your garden looking beautiful without having to lift a finger With Reliable Gardening Professionals',
    width1: 50,
    width2: 50,
    section1Data: [
      'Mowing',
      'Edging',
      'Fertilization',
      'Topiary Services',
      'Mulching Services',
      'Aeration',
      'Lawn',
      'Detaching',
      'Slashing',
    ],
    section2Data: [
      'Mowing',
      'Edging',
      'Fertilization',
      'Topiary Services',
      'Mulching Services',
      'Aeration',
      'Lawn',
      'Detaching',
      'Slashing',
    ],
  },
  {
    id: 3,
    link1: '/gallery/img2.webp',
    link2: '/gallery/img1.webp',
    heading: 'Seasonal Cleanup',
    desc: 'Keep your garden looking beautiful without having to lift a finger With Reliable Gardening Professionals',
    width1: 30,
    width2: 70,
    section1Data: [
      'Mowing',
      'Edging',
      'Fertilization',
      'Topiary Services',
      'Mulching Services',
      'Aeration',
      'Lawn',
      'Detaching',
      'Slashing',
    ],
    section2Data: [
      'Mowing',
      'Edging',
      'Fertilization',
      'Topiary Services',
      'Mulching Services',
      'Aeration',
      'Lawn',
      'Detaching',
      'Slashing',
    ],
  },
  {
    id: 4,
    link1: '/gallery/img7.webp',
    link2: '/gallery/img8.webp',
    link3: '/gallery/img9.webp',
    heading: 'Consultation & Maintenance',
    desc: 'Keep your garden looking beautiful without having to lift a finger With Reliable Gardening Professionals',
    width1: 33,
    width2: 33,
    width3: 33,
    isThree: true,
    section1Data: [
      'Mowing',
      'Edging',
      'Fertilization',
      'Topiary Services',
      'Mulching Services',
      'Aeration',
      'Lawn',
      'Detaching',
      'Slashing',
    ],
    section2Data: [
      'Mowing',
      'Edging',
      'Fertilization',
      'Topiary Services',
      'Mulching Services',
      'Aeration',
      'Lawn',
      'Detaching',
      'Slashing',
    ],
    section3Data: [
      'Mowing',
      'Edging',
      'Fertilization',
      'Topiary Services',
      'Mulching Services',
      'Aeration',
      'Lawn',
      'Detaching',
      'Slashing',
    ],
  },
];

export const reviews = [
  {
    id: 1,
    imageUrl: '/reviews/review1.png',
    name: 'EMILY',
    type: 'toorak',
    desc: "I'm absolutely thrilled with the impeccable lawn mowing service provided by Timmy's's! Living in Toorak, maintaining our garden's elegance is essential, and they've exceeded all expectations. From precise mowing to expert garden care, Timmy's's is a cut above the rest.",
  },
  {
    id: 2,
    imageUrl: '/reviews/review1.png',
    name: 'EMILY',
    type: 'toorak',
    desc: "I'm absolutely thrilled with the impeccable lawn mowing service provided by Timmy's's! Living in Toorak, maintaining our garden's elegance is essential, and they've exceeded all expectations. From precise mowing to expert garden care, Timmy's's is a cut above the rest.",
  },
  {
    id: 3,
    imageUrl: '/reviews/review1.png',
    name: 'EMILY',
    type: 'toorak',
    desc: "I'm absolutely thrilled with the impeccable lawn mowing service provided by Timmy's's! Living in Toorak, maintaining our garden's elegance is essential, and they've exceeded all expectations. From precise mowing to expert garden care, Timmy's's is a cut above the rest.",
  },
  {
    id: 4,
    imageUrl: '/reviews/review1.png',
    name: 'EMILY',
    type: 'toorak',
    desc: "I'm absolutely thrilled with the impeccable lawn mowing service provided by Timmy's's! Living in Toorak, maintaining our garden's elegance is essential, and they've exceeded all expectations. From precise mowing to expert garden care, Timmy's's is a cut above the rest.",
  },
  {
    id: 5,
    imageUrl: '/reviews/review1.png',
    name: 'EMILY',
    type: 'toorak',
    desc: "I'm absolutely thrilled with the impeccable lawn mowing service provided by Timmy's's! Living in Toorak, maintaining our garden's elegance is essential, and they've exceeded all expectations. From precise mowing to expert garden care, Timmy's's is a cut above the rest.",
  },
];

export const cities = {
  1: [
    'Toorak',
    'Brighton',
    'Malvern',
    'Kew',
    'Hawthorn',
    'Canterbury',
    'Camberwell',
    'Balwyn',
    'Surrey Hills',
    'Glen Iris',
  ],
  2: [
    'South Yarra',
    'Armadale',
    'Caulfield',
    'Ivanhoe',
    'Beaumaris',
    'Elsternwick',
    'Hampton',
    'Albert Park',
    'Mount Waverley',
    'Doncaster',
  ],
};

export const pricePageData = {
  Experience:
    'We understand each participants needs are different and will work with you to provide the gardening you require.',

  Reliability:
    'We understand each participants needs are different and will work with you to provide the gardening you require.2',

  Quality:
    'We understand each participants needs are different and will work with you to provide the gardening you require.3',
  img1: '/price.png',
  img2: '/price1.png',
  img3: '/price2.png',
};

export const galleryInfoSm = [
  {
    heading: 'Lawn Care',
    list: [
      'Mowing',
      'Edging',
      'Fertilization',
      'Topiary Services',
      'Mulching Services',
      'Aeration',
      'Lawn',
      'Detaching',
      'Slashing',
    ],
  },
  {
    heading: 'Garden Design',
    list: ['Custom Design', 'Theme gardens', 'Landscaping'],
  },
  {
    heading: 'Weed Control',
    list: ['Weeding', 'Herbicide', 'Application'],
  },
  {
    heading: 'Planting, Grassing & Bedding',
    list: ['Flower Bed Design', 'Plant Installation'],
  },
  {
    heading: 'Seasonal Cleanup',
    list: ['Fall Clean up', 'Spring Clean up'],
  },
  {
    heading: 'Hedge & Tree Care',
    list: [
      'Prunning and Trimming',
      'Tree Lopping',
      'Stump removal',
      'Topiary Services',
    ],
  },
  {
    heading: 'Consultstion & Maintainance',
    list: ['Site Evaluation'],
  },
  {
    heading: 'Pest Management',
    list: ['Identification', 'Treatment'],
  },
  {
    heading: 'Waste Removal Services',
    list: ['Green waste removal', 'Other waste removal', 'Leaf blowing'],
  },
];
